export const copy = {
  title: 'مینی‌اپ طالس',
  currentStatus: 'وضعیت فعلی',
  verifyHeading: 'تأیید شناسۀ XT-UID',
  verifyDescription:
    'دسترسی به خدمات اختصاصی طالس فقط برای کاربرانی فراهم است که با کد طالس در صرافی XT حساب داشته باشند.',
  verifyInstruction: 'لطفاً برای آزاد شدن دسترسی شناسۀ XT-UID خود را وارد کنید.',
  uidLabel: 'شناسۀ XT-UID',
  uidPlaceholder: 'شناسۀ XT-UID را وارد کنید',
  submit: 'ارسال شناسه',
  helperUid: 'راهنمای پیدا کردن UID',
  helperRegistration: 'راهنمای ثبت‌نام با کد طالس',
  support: 'تماس با پشتیبانی',
  back: 'بازگشت',
  loading: 'در حال بررسی...',
  discountTitle: 'دریافت تخفیف ۳۸ دلاری کارت XT',
  discountBody: 'این مزیت فقط برای مشتریان تأییدشده طالس فعال است. جزئیات کامل بعداً اضافه می‌شود.',
  locked: 'این بخش فقط پس از تأیید شناسه در دسترس است.',
  routeUidHelpTitle: 'راهنمای پیدا کردن UID',
  routeRegistrationTitle: 'راهنمای ثبت‌نام با کد طالس',
  routeSupportTitle: 'تماس با پشتیبانی',
  routePlaceholder: 'این صفحه فعلاً خالی است.',
  verificationPending: 'یا شناسه اشتباه وارد شده یا این شناسه با کد طالس ثبت‌نام نکرده است.',
} as const;
